### ISSUE TITLE
Have a way to clear view counts

### ISSUE THREAD

**Issue by zizther** [doublesecretagency/craft-viewcount#2]
My use case is where I have been testing, it would be good to be able to easily clear all view counts. I know this can be done via the database, but it maybe a nice option to have a button and some validation before removing all entries for other users.

This could also get a bit more feature rich where it could remove entries from certain `key` or for a particular entry.

**Comment by lindseydiloreto** [comment]
That's a good idea. It would be nice to have a UI for something like that.

**Comment by compass360** [comment]
I concur that this would be a nice feature. Here's a use case, from my own personal use of this plugin: We're leveraging this plugin to build a "progress tracker", tracking elements that a user has previously viewed, which is pretty powerful since we can utilize both local storage and database (for signed-in users). But giving the ability for users themselves to access something like a "clear my progress" function via a hook of some sort would be super valuable. We'd ideally use it to erase the data associated with a specific user.

**Comment by lindseydiloreto** [comment]
Good news! It's now possible to [set or reset a counter](https://plugins.doublesecretagency.com/view-count/setting-or-resetting-a-counter/) in **v1.2.0**.
